"""Added sales_tax and shipping_cost to Order model

Revision ID: 082d8de043c8
Revises: 
Create Date: 2024-11-09 13:25:18.566040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082d8de043c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_tax', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('sales_tax')

    # ### end Alembic commands ###
